### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by CuongVuTB** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#11]
![image](https://github.com/SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024/assets/152162020/366ca80a-8cf9-455e-80f8-f25bdd515145)
I logged in with 3 accounts, but when I started the tool, only 1 or 2 accounts ran, and then an error occurred. Help me fix this issue, please.

**Comment by SM-FREE-TOOLS** [comment]
Your account got limited by Telegram, you need to login with more accounts.
