### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by belikejoe** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#12]
❯ python3 main.pyc
Traceback (most recent call last):
  File "main1.718.py", line 1, in <module>
ModuleNotFoundError: No module named 'telethon'
    ~/De/-Telegram-Adder-Scraper-Members-NEW-FREE-2024-main 

**Comment by SM-FREE-TOOLS** [comment]
Open cmd and type this: python3 -m pip install telethon

If you need more help, contact us on Telegram: t.me/SubAdder
