### ISSUE TITLE
Can't select Channels

### ISSUE THREAD

**Issue by Popotaso** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#14]
Hello,

I've been trying to use this software to add new member automatically to a channel (NOT A GROUP). When launching the app and inserting number 3 to scrape members from group, I can't see the channel where I would like to scrape member from. This applys boths ways, I can't scrape nor add members to a Channel(NOT A GROUP)

![popotepng](https://github.com/SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024/assets/165707797/999acafc-aed3-4bc9-a123-088baa729a7e)

I saw it works with groups/channels so I'm wondering why the channels wont show up. Is it neccesary for the scraping user to be administrator of this channel?

**Comment by SM-FREE-TOOLS** [comment]
Due to Telegrams update, it has been removed. It is impossible to add into channels once the channel has more than 200 subs. Scraping a channel is also impossible. You will need to scrape groups and add into groups
