### ISSUE TITLE
magic code

### ISSUE THREAD

**Issue by CuongVuTB** [SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024#8]
![image](https://github.com/SM-FREE-TOOLS/-Telegram-Adder-Scraper-Members-NEW-FREE-2024/assets/152162020/51d77c56-a9d8-4d06-9541-1d1a26a33deb)
how to fix this?

**Comment by SM-FREE-TOOLS** [comment]
Update Python to 3.12, while installing make sure to check the option Add to PATH. After that, restart your system.

**Comment by CuongVuTB** [comment]
thank you so much <3
